### PR TITLE
proper raise ArgumentError, divided large text into new line

### PR DESCRIPTION
**Pull request by Gaurav2728**
reference issue https://github.com/rails/rails/pull/21293   @zzak

### CODE REVIEW

**Comment by yui-knk** [comment]
Could you send the PR to rails/rails? docrails don't accept PRs.
And this change includes code changes.

**Comment by Gaurav2728** [comment]
@yui-knk , @rafaelfranca i alreday send the PR in Rails but its closed by "Senny" (saying that issue with how rDoc renders proerly) so sended here. can you please check in Rails  https://github.com/rails/rails/pull/21293. :relaxed:

**Comment by rafaelfranca** [comment]
I see. He pointed that it is a bug on rdoc, so we need to fix it there. This is docrails, not rdoc

**Comment by zzak** [comment]
Is there an issue for this on rdoc yet?

**Comment by Gaurav2728** [comment]
@rafaelfranca thanks :yellow_heart:

**Pull request closed without merging**
