### PR TITLE
Correction to action_mailer_basics

### PR DESCRIPTION
**Pull request by mcshakes**
Not sure if a correction or update. When I run rails generate just like the Guide says, I don't get a UserMailer file that inherits from the ApplicationMailer. Instead, I get a UserMailer that inherits straight away from the ActionMailer::Base. Seems like ApplicationMailer may be outdated, because I've never had it pop up when using the "rails generate". But the docs haven't been updated. Anyway, hope to clear some confusion.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Could you send the PR to rails/rails? docrails don't accept PRs.

**Comment by mcshakes** [comment]
Sure. I'm new at this. Do you have an exact link? I may also edit the docs telling me how to contribute to the docs because this guide:

http://guides.ruby.tw/rails3/contribute.html

 sent me here.

**Comment by rafaelfranca** [comment]
> I'm new at this

Awesome! Welcome and thank you for contributing to Rails.

You just need to send the same patch to https://github.com/rails/rails. You can find more information in  the official guide http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation.

**Comment by mcshakes** [comment]
Oh cool. I'll do that real quick

**Pull request closed without merging**
